apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: httpbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      serviceAccountName: httpbin-sa
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: var-tmp-volume
          emptyDir: {}
        - name: home-volume
          emptyDir: {}
      containers:
      - image: kennethreitz/httpbin:latest
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          # privileged: true
          # runAsUser: 0
          # allowPrivilegeEscalation: true
          # capabilities:
          #   add: ["SYS_ADMIN", "NET_ADMIN"]
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "200m"
            memory: "250Mi"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: var-tmp-volume
          mountPath: /var/tmp
        - name: home-volume
          mountPath: /home/httpbin
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: httpbin
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  # Only schedule on worker nodes
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist